/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.edu.udf.UI;

import br.edu.udf.DAL.CidadeDAL;
import br.edu.udf.DTO.CidadeDTO;
import javax.swing.JOptionPane;

/**
 *
 * @author joao1
 */
public class frmCidades extends javax.swing.JFrame {
    CidadeDAL dal = new CidadeDAL();
    CidadeDTO cidade = new CidadeDTO();
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frmCidades.class.getName());

    /**
     * Creates new form frmCidades
     */
    public frmCidades() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtCodCid = new javax.swing.JTextField();
        btnPesquisarCidID = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNomeCid = new javax.swing.JTextField();
        txtCepCid = new javax.swing.JTextField();
        btnCadastroCid = new javax.swing.JButton();
        btnAlterarCid = new javax.swing.JButton();
        btnExcluirCid = new javax.swing.JButton();
        btnMostrarCid = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        dvgCidades = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Cadastro de Cidades");
        setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        setResizable(false);

        jLabel1.setText("ID da cidade");

        btnPesquisarCidID.setText("Pesquisar");
        btnPesquisarCidID.addActionListener(this::btnPesquisarCidIDActionPerformed);

        jLabel2.setText("Nome da Cidade");

        jLabel3.setText("CEP da Cidade");

        txtNomeCid.addActionListener(this::txtNomeCidActionPerformed);

        txtCepCid.addActionListener(this::txtCepCidActionPerformed);

        btnCadastroCid.setText("Cadastrar");
        btnCadastroCid.addActionListener(this::btnCadastroCidActionPerformed);

        btnAlterarCid.setText("Alterar");
        btnAlterarCid.addActionListener(this::btnAlterarCidActionPerformed);

        btnExcluirCid.setText("Excluir");

        btnMostrarCid.setText("Exibir Todas as Cidades");

        btnLimpar.setText("Limpar");

        btnSair.setText("Sair");

        dvgCidades.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Cidade ID", "Nome da Cidade", "CEP da cidade"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Long.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(dvgCidades);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(130, 130, 130)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCepCid, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNomeCid, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(67, 67, 67)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCadastroCid)
                            .addComponent(btnAlterarCid)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtCodCid, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67)
                        .addComponent(btnPesquisarCidID)))
                .addContainerGap(334, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnMostrarCid)
                        .addGap(34, 34, 34)
                        .addComponent(btnExcluirCid))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSair)
                        .addGap(26, 26, 26)
                        .addComponent(btnLimpar)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCodCid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisarCidID))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNomeCid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCadastroCid))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCepCid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAlterarCid))))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMostrarCid)
                    .addComponent(btnExcluirCid))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSair)
                    .addComponent(btnLimpar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 479, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastroCidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastroCidActionPerformed
        // TODO add your handling code here:
        try {
// fazendo a validação dos dados
            if (txtNomeCid.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "O campo Nome da Cidade está vazio!!!!");
txtNomeCid.requestFocus();
            }
             else if (txtCepCid.getText().equals(" . . - ")) {
                JOptionPane.showMessageDialog(null, "O campo CEP da Cidade está vazio !!!!");
                txtCepCid.requestFocus();
            } else {
                try {
// Abre conexão somente após validação
                    dal.abrirBD();
                    cidade.setCidNome(txtNomeCid.getText());
                    cidade.setCidCEP(txtCepCid.getText());
//Chama o método incluirCliente da camada DAL
                    dal.incluirCidade(cidade);
                    JOptionPane.showMessageDialog(null, "Cidade " + txtNomeCid.getText() + " incluído com sucesso!");
// Limpa os campos
                    txtNomeCid.setText("");
                    txtCepCid.setText("");
                    txtNomeCid.requestFocus();
                    btnMostrarCid.setEnabled(true);
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(null, "Erro na inclusão: "
                            + ex.getMessage());
                } finally {
// Garante que a conexão seja fechada
                    try {
                        dal.fecharBD();
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, "Erro ao fechar conexão: "
                                + e.getMessage());
                    }
                }
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Erro desconhecido: " + ex.getMessage());
        }
    }//GEN-LAST:event_btnCadastroCidActionPerformed

    private void txtNomeCidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeCidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeCidActionPerformed

    private void txtCepCidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCepCidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCepCidActionPerformed

    private void btnAlterarCidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarCidActionPerformed
        // TODO add your handling code here:
        try {
            dal.abrirBD();
            if (txtCodCid.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "O campo Código do Cliente está vazio!!!!");
                txtCodCid.requestFocus();
            } else if (txtNomeCid.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "O campo Nome do Cliente está vazio!!!!");
                txtNomeCid.requestFocus();
            } else if (txtCepCid.getText().equals(" . . - ")) {
                JOptionPane.showMessageDialog(null, "O campo CPF do Cliente está vazio!!!!");
                txtCepCid.requestFocus();
            } else {
                cidade.setCidId((int) Long.parseLong(txtCodCid.getText()));
                cidade.setCidNome(txtNomeCid.getText());
                cliente.setCliEndereco(txtEnderecoCli.getText());
                cliente.setCliCPF(txtCPFCli.getText());
                try {
                    dal.alterarCliente(cliente);
                    JOptionPane.showMessageDialog(null, "Cliente " + cliente.getCliNome() + "
Alterado Com Sucesso !!!!");
// Limpa os campos
txtCodigoCli.setText(null);
                    txtNomeCli.setText(null);
                    txtEnderecoCli.setText(null);
                    txtCPFCli.setText(null);
                    txtCodigoCli.requestFocus();
                    btnMostrarTodosCli.setEnabled(true);
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(null, "Erro Na Conexão: "
                            + ex.getMessage());
                }
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Erro ao processar alteração: "
                    + ex.getMessage());
        } finally {
            try {
                dal.fecharBD();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Erro ao fechar conexão: "
                        + e.getMessage());
            }
        }
    }//GEN-LAST:event_btnAlterarCidActionPerformed

    private void btnPesquisarCidIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarCidIDActionPerformed
        // TODO add your handling code here:
        //Verifica se o código do cliente está vazio
        if ("".equals(txtCodCid.getText())) {
            JOptionPane.showMessageDialog(null, "Código do Cliente não pode ser vazio, favor digite um código válido !!!!");
//Após a mensagem de erro, o foco do cursor vai ficar no campo Código do Cliente
 txtCodCid.requestFocus();
        } else {
//Faz o tratamento de erro, para verificar se a tabela Clientes está vazia
//O botão Incluir vai ficar dsesabilitado
            btnCadastroCid.setEnabled(false);
//O botão Alterar vai ficar habilitado
            btnAlterarCid.setEnabled(true);
//O botão Excluir vai ficar habilitado
            btnExcluirCid.setEnabled(true);
//O botão Mostrar Todos vai ficar habilitado
            btnMostrarCid.setEnabled(true);
            try {
//Chama o método selecionarClientePorID da classe ClienteDAL
                cidade = dal.selecionarCidadePorID(Integer.valueOf(txtCodCid.getText()));
                if (txtCodCid != null) {
//Mostra os dados do Cliente pelo seu código
                    txtNomeCid.setText(cidade.getCidNome());
                    txtCepCid.setText(cidade.getCidCEP());
                   
                } else {
                    JOptionPane.showMessageDialog(null, "Cliente Não Encontrado. Favor Tente Novamente !!!!");
// Limpa os campos
                    txtNomeCid.setText(null);
                    txtCepCid.setText(null);
                    txtNomeCid.requestFocus();
                    txtCodCid.setText(null);
                    txtCodCid.requestFocus();
                    btnCadastroCid.setEnabled(true);
                }
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "Erro ao Buscar Cliente. Favor Tente Novamente !!!!");
                txtCodCid.setText(null);
                txtCodCid.requestFocus();
            }
        }
    }//GEN-LAST:event_btnPesquisarCidIDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new frmCidades().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterarCid;
    private javax.swing.JButton btnCadastroCid;
    private javax.swing.JButton btnExcluirCid;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnMostrarCid;
    private javax.swing.JButton btnPesquisarCidID;
    private javax.swing.JButton btnSair;
    private javax.swing.JTable dvgCidades;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtCepCid;
    private javax.swing.JTextField txtCodCid;
    private javax.swing.JTextField txtNomeCid;
    // End of variables declaration//GEN-END:variables
}
