/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/MDIApplication.java to edit this template
 */
package br.edu.udf.UI;

import br.edu.udf.DAL.CidadeDAL;
import br.edu.udf.DTO.CidadeDTO;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 *
 * @author joao1
 */
public class frmPrincipal extends javax.swing.JFrame {
    // instanciando a classe ClienteDTO do pacote DTO e criando seu objeto cliente

    CidadeDTO cidade = new CidadeDTO();
// Instancia a classe ClientesDAL
    CidadeDAL dal = new CidadeDAL();
    /**
     * Creates new form frmPrincipal
     */
    public frmPrincipal() {
        initComponents();
        inserirIcone();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuBar = new javax.swing.JMenuBar();
        mnuAppCidade = new javax.swing.JMenu();
        itmSair = new javax.swing.JMenuItem();
        mnuCadastro = new javax.swing.JMenu();
        itmCadCid = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Cadastro de Cidades");
        setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        setResizable(false);

        mnuAppCidade.setMnemonic('f');
        mnuAppCidade.setText("Aplicativo Cadastro de Cidade");

        itmSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        itmSair.setMnemonic('x');
        itmSair.setText("Sair");
        itmSair.addActionListener(this::itmSairActionPerformed);
        mnuAppCidade.add(itmSair);

        menuBar.add(mnuAppCidade);

        mnuCadastro.setText("Nova Cidade");

        itmCadCid.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        itmCadCid.setText("Cidade");
        itmCadCid.addActionListener(this::itmCadCidActionPerformed);
        mnuCadastro.add(itmCadCid);

        menuBar.add(mnuCadastro);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void itmSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmSairActionPerformed
        Object[] opcoes = {"Sim", "Não"};
        int contador = JOptionPane.showOptionDialog(null, "Deseja Sair do Sistema? ",
                "Cadastro de Clientes", JOptionPane.YES_OPTION, JOptionPane.QUESTION_MESSAGE,
                null, opcoes, opcoes[0]);
        if (contador == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_itmSairActionPerformed

    private void itmCadCidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmCadCidActionPerformed
        // TODO add your handling code here:
        //Verfica se o formulário é nulo e está visivel
        if ((frmCidades == null) || (!frmCidades.isVisible())) {
            frmCidades = new frmCidades();
            frmCidades.setVisible(true);
        }
    }//GEN-LAST:event_itmCadCidActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itmCadCid;
    private javax.swing.JMenuItem itmSair;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu mnuAppCidade;
    private javax.swing.JMenu mnuCadastro;
    // End of variables declaration//GEN-END:variables

    private void inserirIcone() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("iconecidade.png")));
    }
    
    //Declarando o objeto formClientes
    private frmCidades frmCidades;

}
